/******************* Generated by FEGO Transformer Logic *******************/
package com.cognizant.cde;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import java.util.Arrays;
import javax.servlet.Filter;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter;

@Configuration()
public class FilterBeanConfiguration {

    @Bean()
    public FilterRegistrationBean struts2() {
        return buildFilterRegistration(1, new StrutsPrepareAndExecuteFilter(), "/*");
    }

    private FilterRegistrationBean buildFilterRegistration(int order, Filter filter, String... urlPatterns) {
        FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(filter);
        registration.setUrlPatterns(Arrays.asList(urlPatterns));
        registration.setOrder(order);
        return registration;
    }
}
